# ==========================
# = Spring
# ==========================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.ctvx8oj4fjyg.sa-east-1.rds.amazonaws.com:3306/realmeet?serverTimezone=UTC&useSSL=false
    username: admin